DATASOURCE/DATASOURCE/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('data.urls',namespace="data")),
]

DATASOURCE/data/urls.py
from django.conf.urls import url

from  . import views

urlpatterns = [
    url(r'^add/$',views.add_data,name='add_data'),

]
app_name='data'

DATASOURCE/data/models.py
from django.db import models
import django.utils.timezone as timezone
# Create your models here.
class datacollect(models.Model):
    date=models.CharField(max_length=20)
    cities=models.CharField(max_length=20)
    level=models.CharField(max_length=20)
    date_added=models.DateTimeField(auto_now_add=True)
class data_c(models.Model):
    city=models.CharField(max_length=20)
    province=models.CharField(max_length=20)
    level=models.CharField(max_length=20)
    disease=models.CharField(max_length=20)
    time=models.DateField()

DATASOURCE/data/forms.py
from django import forms
from .models import datacollect,data_c
class form(forms.ModelForm):
    class Meta:
        model=datacollect
        fields = ['date','cities','level']
        labels = {'date':'','cities':'','level':''}

class data_form(forms.ModelForm):
    class Meta:
        model=data_c
        fields = ['city','province','level','disease','time']
        labels = {'city':'','province':'','level':'','disease':'','time':''}

DATASOURCE/data/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import form,data_form
import pymysql
# Create your views here.


'''
def add(request):
    # ------------------------------------------------获取到已经提交的数据，用于展示-------------------------------------------
    connect = pymysql.connect(
        host='cdb-hdoxzwau.cd.tencentcdb.com',
        port=10079,
        user='root',
        passwd='lunyang12',
        db='data',
        charset='utf8'
    )
    db = connect.cursor()
    sql = "SELECT cities,level,date_added from data_datacollect"
    db.execute(sql)
    data_show = db.fetchall()
    db.close()
    connect.close()
    # -------------------------------------------------------------------------------------------------------------------------


    if request.method == 'POST':
        data=form(request.POST)
        if data.is_valid():
            level=request.POST.get('level','')
            city=request.POST.get('cities','')
            date=request.POST.get('date','')

            #------------------------------------------------用于获取已经存在的数据----------------------------------------------------
            connect = pymysql.connect(
                host='cdb-hdoxzwau.cd.tencentcdb.com',
                port=10079,
                user='root',
                passwd='lunyang12',
                db='data',
                charset='utf8'
            )
            db = connect.cursor()
            sql1= "SELECT cities,level1,level2,level3,level4,date from DATA WHERE cities='"+str(city)+"'"+"AND"+" date='"+str(date)+"'"
            db.execute(sql1)
            data_exist = db.fetchone()
            db.close()
            connect.close()

            #------------------------------------------------用于获取已经存在的数据----------------------------------------------------
                # -------------------------------------用于更新存在的数据------------------------------------------------------------------
            if data_exist:
                data_now=data_exist[int(level)]+1
                connect = pymysql.connect(
                    host='cdb-hdoxzwau.cd.tencentcdb.com',
                    port=10079,
                    user='root',
                    passwd='lunyang12',
                    db='data',
                    charset='utf8'
                )
                db = connect.cursor()
                sql2="UPDATE DATA SET level"+str(level)+"=%s WHERE cities=%s AND date=%s"
                try:
                    db.execute(sql2,[data_now,city,date])
                    connect.commit()
                except:
                    # 有异常，回滚事务
                    connect.rollback()
                    return HttpResponse('提交失败')
                db.close()
                connect.close()
                # -------------------------------------------------------------------------------------------------------------------------

            elif not data_exist:

                # --------------------------用于创建没有的数据-----------------------------------------------------------------------------
                connect = pymysql.connect(
                    host='cdb-hdoxzwau.cd.tencentcdb.com',
                    port=10079,
                    user='root',
                    passwd='lunyang12',
                    db='data',
                    charset='utf8'
                )
                db = connect.cursor()
                sql2 = "INSERT INTO DATA(cities,level1,level2,level3,level4,date) VALUES (%s,%s,%s,%s,%s,%s)"
                try:
                    if int(level)==1:
                        db.execute(sql2, [city,1,0,0,0, date])
                    elif int(level) ==2:
                        db.execute(sql2, [city,0, 1, 0,0, date])
                    elif int(level) ==3:
                        db.execute(sql2, [city,0, 0, 1,0, date])
                    elif int(level) ==4:
                        db.execute(sql2, [city,0, 0, 0,1, date])
                    connect.commit()
                except:
                    # 有异常，回滚事务
                    connect.rollback()
                    return HttpResponse('提交失败')
                db.close()
                connect.close()
                # -------------------------------------------------------------------------------------------------------------------------
            # --------------------------------------------更新总数据-----------------------------------------------------------------------------
            connect = pymysql.connect(
                    host='cdb-hdoxzwau.cd.tencentcdb.com',
                    port=10079,
                    user='root',
                    passwd='lunyang12',
                    db='data',
                    charset='utf8'
                )
            db = connect.cursor()
            sql1 = "SELECT number from DATA_ALL WHERE cities='" + str(city) + "'"
            db.execute(sql1)
            data_exist_all = db.fetchone()
            data_exist_all_now = data_exist_all[0] + 1
            sql2 = "UPDATE DATA_ALL SET number=%s WHERE cities=%s"
            try:
                db.execute(sql2, [data_exist_all_now, city])
                connect.commit()
            except:
                # 有异常，回滚事务
                connect.rollback()
                return HttpResponse('提交失败')
                db.close()
                connect.close()

                # -------------------------------------------------------------------------------------------------------------------------
            data.save()
            return HttpResponse('提交成功')
    else:
        data=form()
    return render(request,'add.html',{'data':data,'data_show':data_show})
'''



def add_data(request):
    if request.method == 'POST':
        form=data_form(request.POST)
        if form.is_valid():
            city=request.POST.get('city','')
            province=request.POST.get('province','')
            level=request.POST.get('level','')
            disease = request.POST.get('disease', '')
            time=request.POST.get('time','')
            # ------------------------------------------------用于获取已经存在的数据----------------------------------------------------
            connect = pymysql.connect(
                host='cdb-hdoxzwau.cd.tencentcdb.com',
                port=10079,
                user='root',
                passwd='lunyang12',
                db='data',
                charset='utf8'
            )
            db = connect.cursor()
            sql1 = "SELECT city,province,level,disease,time,number from DATA_cq WHERE city='" + str(city) + "'" + "AND" + " time='" + str(time) +"'"+ "AND"+ " province='"+str(province)+"'"+"AND"+ " disease='"+str(disease)+"'"
            db.execute(sql1)
            data_exist = db.fetchone()
            db.close()
            connect.close()

            # ------------------------------------------------用于获取已经存在的数据----------------------------------------------------

            # -------------------------------------用于更新存在的数据------------------------------------------------------------------
            if data_exist:
                data_now = data_exist[5] + 1
                connect = pymysql.connect(
                    host='cdb-hdoxzwau.cd.tencentcdb.com',
                    port=10079,
                    user='root',
                    passwd='lunyang12',
                    db='data',
                    charset='utf8'
                )
                db = connect.cursor()
                sql2 = "UPDATE DATA_cq SET number=%s WHERE city=%s AND time=%s AND disease=%s AND province=%s"
                try:
                    db.execute(sql2, [data_now, city, time,disease,province])
                    connect.commit()
                except:
                    # 有异常，回滚事务
                    connect.rollback()
                    return HttpResponse('提交失败')
                db.close()
                connect.close()
                # -------------------------------------------------------------------------------------------------------------------------

            elif not data_exist:

                # --------------------------用于创建没有的数据-----------------------------------------------------------------------------
                connect = pymysql.connect(
                    host='cdb-hdoxzwau.cd.tencentcdb.com',
                    port=10079,
                    user='root',
                    passwd='lunyang12',
                    db='data',
                    charset='utf8'
                )
                db = connect.cursor()
                sql2 = "INSERT INTO DATA_cq(city,province,level,disease,time,number) VALUES (%s,%s,%s,%s,%s,%s)"
                try:
                    db.execute(sql2, [city, province, level, disease,time, 1])
                    connect.commit()
                except:
                    # 有异常，回滚事务
                    connect.rollback()
                    return HttpResponse('提交失败')
                db.close()
                connect.close()
                # -------------------------------------------------------------------------------------------------------------------------
#总数据

           # ------------------------------------------------用于获取已经存在的数据----------------------------------------------------
            connect = pymysql.connect(
                    host='cdb-hdoxzwau.cd.tencentcdb.com',
                    port=10079,
                    user='root',
                    passwd='lunyang12',
                    db='data',
                    charset='utf8'
                )
            db = connect.cursor()
            sql1 = "SELECT city,level,time,number from DATA_ALL WHERE city='" + str(city) + "'" + "AND" + " time='" + str(time) + "'"+ "AND" + " level='" + str(level) + "'"
            db.execute(sql1)
            data_exist_all = db.fetchone()
            db.close()
            connect.close()

DATASOURCE/data/templates/add.html
<form action="{% url 'data:add' %}" method='POST'>
	{% csrf_token %}
     城市
    <select name="cities">
        <option value="">请选择城市</option>
        <option value="安徽">安徽</option>
        <option value="北京">北京</option>
        <option value="重庆">重庆</option>
        <option value="福建">福建</option>
        <option value="甘肃">甘肃</option>
        <option value="广东">广东</option>
        <option value="广西壮族自治区">广西壮族自治区</option>
        <option value="贵州">贵州</option>
        <option value="海南">海南</option>
        <option value="河北">河北</option>
        <option value="黑龍江省">黑龍江省</option>
        <option value="河南">河南</option>
        <option value="湖北">湖北</option>
        <option value="湖南">湖南</option>
        <option value="江苏">江苏</option>
        <option value="江西">江西</option>
        <option value="吉林">吉林</option>
        <option value="辽宁">辽宁</option>
        <option value="内蒙古自治区">内蒙古自治区</option>
        <option value="宁夏回族自治区">宁夏回族自治区</option>
        <option value="青海">青海</option>
        <option value="陕西">陕西</option>
        <option value="山东">山东</option>
        <option value="上海">上海</option>
        <option value="山西">山西</option>
        <option value="四川">四川</option>
        <option value="天津">天津</option>
        <option value="新疆维吾尔自治区">新疆维吾尔自治区</option>
    </select>
    类别
    <select name="level">
        <option value="">请选择类别</option>
        <option value="1">丙类</option>
        <option value="2">乙类</option>
        <option value="3">甲类</option>
        <option value="4">未知传染病（待命名）</option>

    </select>
    日期(xxxx xx xx):
    <input type="text" name="date">
    <button name="submit">添加记录</button>
</form>
<ul>
    {%for data in data_show%}
<li>
    {%for  dat in data%}
    {{dat}}
    {%endfor%}
</li>
    {%endfor%}
</ul>

DATASOURCE/data/templates/add_data_cq.html
<!DOCTYPE HTML>
目前只开放重庆地区
<form action="{% url 'data:add_data' %}" method='POST'>
	{% csrf_token %}
     地区
    <select name="city">
        <option value="重庆">重庆</option>
    </select>
    区县
    <select name="province">
        <option value="">请选择区县</option>
        <option value="巴南区">巴南区</option>
        <option value="璧山区">璧山区</option>
        <option value="长寿区">长寿区</option>
        <option value="城口">城口</option>
        <option value="重庆">重庆</option>
        <option value="大足">大足</option>
        <option value="垫江">垫江</option>
        <option value="丰都">丰都</option>
        <option value="奉节">奉节</option>
        <option value="涪陵">涪陵</option>
        <option value="合川">合川</option>
        <option value="江北">江北</option>
        <option value="江津">江津</option>
        <option value="开县">开县</option>
        <option value="梁平">梁平</option>
        <option value="南川">南川</option>
        <option value="彭水">彭水</option>
        <option value="黔江">黔江</option>
        <option value="綦江">綦江</option>
        <option value="荣川">荣川</option>
        <option value="石柱">石柱</option>
        <option value="铜梁">铜梁</option>
        <option value="潼南">潼南</option>
        <option value="万州">万州</option>
        <option value="武隆">武隆</option>
        <option value="巫山">巫山</option>
        <option value="巫溪">巫溪</option>
        <option value="秀水">秀水</option>
        <option value="永川">永川</option>
        <option value="云阳">酉阳</option>
        <option value="忠县">忠县</option>
    </select>
    传染疾病类别
    <select name="level">
        <option value="">请选择类别</option>
        <option value="丙类">丙类</option>
        <option value="乙类">乙类</option>
        <option value="甲类">甲类</option>
    </select>
    疾病种类
    <select name="disease">
        <option value="">请选择类别</option>
        <option value="">#####甲类#####</option>
        <option value="鼠疫">鼠疫</option>
        <option value="霍乱">霍乱</option>
        <option value="">#####乙类#####</option>
        <option value="新型冠状病毒肺炎">新型冠状病毒肺炎</option>
        <option value="结核病">结核病</option>
        <option value="登革热">登革热</option>
        <option value="血吸虫病">血吸虫病</option>
        <option value="艾滋病">艾滋病</option>
        <option value="狂犬病">狂犬病</option>
        <option value="人感染H7N9禽流感">人感染H7N9禽流感</option>
        <option value="疟疾">疟疾</option>
        <option value="麻疹">麻疹</option>
        <option value="传染性非典型肺炎">传染性非典型肺炎</option>
        <option value="">#####丙类#####</option>
        <option value="感染性腹泻病">感染性腹泻病</option>
        <option value="麻风病">麻风病</option>
        <option value="黑热病">黑热病</option>
        <option value="流行性腮腺炎">流行性腮腺炎</option>
        <option value="包虫病">包虫病</option>
    </select>
    日期
    <input type="date" name="time">
    <button name="submit">添加记录</button>
</form>

DATASOURCE/data/templates/advice.html
<h2>出门建议:</h2>
{%for advice in advices%}
<ul><li><h3>
    {{advice.date}}:
    {{advice.advice}}
</h3></li></ul>
{%endfor%}